name: FactionWars
version: '${project.version}'
main: com.factionkingdom.factionwars.FactionWars
api-version: 1.18
authors: [ IncoherentButter ]
description: Faction Combat Plugin
depend: [WorldEdit, WorldGuard, Factions, Vault]
commands:
  factionwars:
    description: Base command
    aliases: [factionwars, fw]
  factionwarscreate:
    description: Creation command
    aliases: [factionwarscreate, fwc]
  factionwarstournament:
    description: Base tournament command
    aliases: [factionwarstournament, factionwarstourney, fwt]
  factionwarstournamentcreate:
    description: Create a tournament
    aliases: [factionwarstournamentcreate, factionwarstourneycreate, fwtc]
