name: FactionWars
version: '1.0-SNAPSHOT'
main: com.factionkingdom.factionwars.FactionWars
api-version: 1.18
authors: [ IncoherentButter ]
description: Faction Combat Plugin
depend: [WorldEdit, WorldGuard, Vault, Factions]
#depend: [WorldEdit, WorldGuard, Vault, FactionsBridge]
#softdepend: [Factions, FactionsX, FactionsBlue, KingdomsX, Kingdoms, LegacyFactions, MedievalFactions, UltimateFactions, Towny]

commands:
  factionwars:
    description: Base command
    aliases: [fw]
  factionwarscreate:
    description: Creation command
    aliases: [fwc]
  factionwarstournament:
    description: Base tournament command
    aliases: [factionwarstourney, fwt]
  factionwarstournamentcreate:
    description: Create a tournament
    aliases: [factionwarstourneycreate, fwtc]
  factionsbridge:
    aliases: [fbridge, factionbridge, facbridge, bridgefactions ]
    description: "Main and only command."
